package SCPCraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class SCPModel217Pig extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer Leg4Extension;
    ModelRenderer Leg4Foot;
    ModelRenderer Nose;
    ModelRenderer Noserim1;
    ModelRenderer Noserim2;
    ModelRenderer Noserim3;
    ModelRenderer Noserim4;
    ModelRenderer Noserim5;
    ModelRenderer Noserim6;
    ModelRenderer BigRim1;
    ModelRenderer LittleRim;
    ModelRenderer LittleRim1;
    ModelRenderer LittleRim2;
    ModelRenderer LittleRim3;
    ModelRenderer Leg4Pipe;
    ModelRenderer bodypart1;
    ModelRenderer bodypart2;
    ModelRenderer Flesh1;
    ModelRenderer Flesh2;
    ModelRenderer Pipe;
  
  public SCPModel217Pig()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -4F, -8F, 8, 8, 8);
      head.setRotationPoint(0F, 12F, -6F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 28, 8);
      body.addBox(-2F, -10F, -7F, 7, 16, 8);
      body.setRotationPoint(0F, 11F, 3F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 1.570796F, 0F, 0F);
      leg1 = new ModelRenderer(this, 0, 16);
      leg1.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg1.setRotationPoint(-3F, 18F, 7F);
      leg1.setTextureSize(64, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 16);
      leg2.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg2.setRotationPoint(3F, 18F, 7F);
      leg2.setTextureSize(64, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 16);
      leg3.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg3.setRotationPoint(-3F, 18F, -5F);
      leg3.setTextureSize(64, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 1, 57);
      leg4.addBox(-2F, 0F, -2F, 4, 2, 4);
      leg4.setRotationPoint(3F, 18F, -5F);
      leg4.setTextureSize(64, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      Leg4Extension = new ModelRenderer(this, 18, 55);
      Leg4Extension.addBox(1F, 2F, -2F, 1, 4, 4);
      Leg4Extension.setRotationPoint(3F, 18F, -5F);
      Leg4Extension.setTextureSize(64, 64);
      Leg4Extension.mirror = true;
      setRotation(Leg4Extension, 0F, 0F, 0F);
      Leg4Foot = new ModelRenderer(this, 29, 58);
      Leg4Foot.addBox(-2F, 5F, -2F, 3, 1, 4);
      Leg4Foot.setRotationPoint(3F, 18F, -5F);
      Leg4Foot.setTextureSize(64, 64);
      Leg4Foot.mirror = true;
      setRotation(Leg4Foot, 0F, 0F, 0F);
      Nose = new ModelRenderer(this, 2, 37);
      Nose.addBox(-2F, 0F, -9F, 4, 3, 1);
      Nose.setRotationPoint(0F, 12F, -6F);
      Nose.setTextureSize(64, 64);
      Nose.mirror = true;
      setRotation(Nose, 0F, 0F, 0F);
      Noserim1 = new ModelRenderer(this, 5, 34);
      Noserim1.addBox(2F, 1F, -9F, 1, 1, 1);
      Noserim1.setRotationPoint(0F, 12F, -6F);
      Noserim1.setTextureSize(64, 64);
      Noserim1.mirror = true;
      setRotation(Noserim1, 0F, 0F, 0F);
      Noserim2 = new ModelRenderer(this, 5, 34);
      Noserim2.addBox(-3F, 1F, -9F, 1, 1, 1);
      Noserim2.setRotationPoint(0F, 12F, -6F);
      Noserim2.setTextureSize(64, 64);
      Noserim2.mirror = true;
      setRotation(Noserim2, 0F, 0F, 0F);
      Noserim3 = new ModelRenderer(this, 5, 34);
      Noserim3.addBox(-1F, 3F, -9F, 1, 1, 1);
      Noserim3.setRotationPoint(0F, 12F, -6F);
      Noserim3.setTextureSize(64, 64);
      Noserim3.mirror = true;
      setRotation(Noserim3, 0F, 0F, 0F);
      Noserim4 = new ModelRenderer(this, 5, 34);
      Noserim4.addBox(0F, 3F, -9F, 1, 1, 1);
      Noserim4.setRotationPoint(0F, 12F, -6F);
      Noserim4.setTextureSize(64, 64);
      Noserim4.mirror = true;
      setRotation(Noserim4, 0F, 0F, 0F);
      Noserim5 = new ModelRenderer(this, 5, 34);
      Noserim5.addBox(0F, -1F, -9F, 1, 1, 1);
      Noserim5.setRotationPoint(0F, 12F, -6F);
      Noserim5.setTextureSize(64, 64);
      Noserim5.mirror = true;
      setRotation(Noserim5, 0F, 0F, 0F);
      Noserim6 = new ModelRenderer(this, 5, 34);
      Noserim6.addBox(-1F, -1F, -9F, 1, 1, 1);
      Noserim6.setRotationPoint(0F, 12F, -6F);
      Noserim6.setTextureSize(64, 64);
      Noserim6.mirror = true;
      setRotation(Noserim6, 0F, 0F, 0F);
      BigRim1 = new ModelRenderer(this, 17, 27);
      BigRim1.addBox(3F, -2F, 1F, 4, 4, 1);
      BigRim1.setRotationPoint(0F, 11F, 3F);
      BigRim1.setTextureSize(64, 64);
      BigRim1.mirror = true;
      setRotation(BigRim1, 0F, 0F, 0F);
      LittleRim = new ModelRenderer(this, 5, 34);
      LittleRim.addBox(4F, -3F, 1F, 1, 1, 1);
      LittleRim.setRotationPoint(0F, 11F, 3F);
      LittleRim.setTextureSize(64, 64);
      LittleRim.mirror = true;
      setRotation(LittleRim, 0F, 0F, 0F);
      LittleRim1 = new ModelRenderer(this, 5, 34);
      LittleRim1.addBox(6F, -3F, 1F, 1, 1, 1);
      LittleRim1.setRotationPoint(0F, 11F, 3F);
      LittleRim1.setTextureSize(64, 64);
      LittleRim1.mirror = true;
      setRotation(LittleRim1, 0F, 0F, 0F);
      LittleRim2 = new ModelRenderer(this, 5, 34);
      LittleRim2.addBox(7F, -2F, 1F, 1, 1, 1);
      LittleRim2.setRotationPoint(0F, 11F, 3F);
      LittleRim2.setTextureSize(64, 64);
      LittleRim2.mirror = true;
      setRotation(LittleRim2, 0F, 0F, 0F);
      LittleRim3 = new ModelRenderer(this, 5, 34);
      LittleRim3.addBox(7F, 0F, 1F, 1, 1, 1);
      LittleRim3.setRotationPoint(0F, 11F, 3F);
      LittleRim3.setTextureSize(64, 64);
      LittleRim3.mirror = true;
      setRotation(LittleRim3, 0F, 0F, 0F);
      Leg4Pipe = new ModelRenderer(this, 2, 51);
      Leg4Pipe.addBox(-1F, 2F, -1F, 1, 3, 2);
      Leg4Pipe.setRotationPoint(3F, 18F, -5F);
      Leg4Pipe.setTextureSize(64, 64);
      Leg4Pipe.mirror = true;
      setRotation(Leg4Pipe, 0F, 0F, 0F);
      bodypart1 = new ModelRenderer(this, 13, 40);
      bodypart1.addBox(-5F, -1F, 0F, 3, 8, 6);
      bodypart1.setRotationPoint(0F, 11F, 3F);
      bodypart1.setTextureSize(64, 64);
      bodypart1.mirror = true;
      setRotation(bodypart1, 0F, 0F, 0F);
      bodypart2 = new ModelRenderer(this, 47, 50);
      bodypart2.addBox(-5F, -1F, -10F, 3, 8, 5);
      bodypart2.setRotationPoint(0F, 11F, 3F);
      bodypart2.setTextureSize(64, 64);
      bodypart2.mirror = true;
      setRotation(bodypart2, 0F, 0F, 0F);
      Flesh1 = new ModelRenderer(this, 32, 33);
      Flesh1.addBox(-5F, -1F, -5F, 3, 3, 5);
      Flesh1.setRotationPoint(0F, 11F, 3F);
      Flesh1.setTextureSize(64, 64);
      Flesh1.mirror = true;
      setRotation(Flesh1, 0F, 0F, 0F);
      Flesh2 = new ModelRenderer(this, 47, 42);
      Flesh2.addBox(-5F, 5F, -5F, 3, 2, 5);
      Flesh2.setRotationPoint(0F, 11F, 3F);
      Flesh2.setTextureSize(64, 64);
      Flesh2.mirror = true;
      setRotation(Flesh2, 0F, 0F, 0F);
      Pipe = new ModelRenderer(this, 15, 33);
      Pipe.addBox(-4F, 3F, -5F, 1, 1, 5);
      Pipe.setRotationPoint(0F, 11F, 3F);
      Pipe.setTextureSize(64, 64);
      Pipe.mirror = true;
      setRotation(Pipe, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.render(f5);
    body.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    Leg4Extension.render(f5);
    Leg4Foot.render(f5);
    Nose.render(f5);
    Noserim1.render(f5);
    Noserim2.render(f5);
    Noserim3.render(f5);
    Noserim4.render(f5);
    Noserim5.render(f5);
    Noserim6.render(f5);
    BigRim1.render(f5);
    LittleRim.render(f5);
    LittleRim1.render(f5);
    LittleRim2.render(f5);
    LittleRim3.render(f5);
    Leg4Pipe.render(f5);
    bodypart1.render(f5);
    bodypart2.render(f5);
    Flesh1.render(f5);
    Flesh2.render(f5);
    Pipe.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.rotateAngleX = f4 / (180F / (float)Math.PI);
    head.rotateAngleY = f3 / (180F / (float)Math.PI);
    body.rotateAngleX = ((float)Math.PI / 2F);
    leg1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    leg2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    leg3.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    leg4.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    Leg4Extension.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    Leg4Foot.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    Noserim1.rotateAngleX = f4 / (180F / (float)Math.PI);
    Noserim2.rotateAngleX = f4 / (180F / (float)Math.PI);
    Noserim3.rotateAngleX = f4 / (180F / (float)Math.PI);
    Noserim4.rotateAngleX = f4 / (180F / (float)Math.PI);
    Noserim5.rotateAngleX = f4 / (180F / (float)Math.PI);
    Noserim6.rotateAngleX = f4 / (180F / (float)Math.PI);
    Noserim1.rotateAngleY = f3 / (180F / (float)Math.PI);
    Noserim2.rotateAngleY = f3 / (180F / (float)Math.PI);
    Noserim3.rotateAngleY = f3 / (180F / (float)Math.PI);
    Noserim4.rotateAngleY = f3 / (180F / (float)Math.PI);
    Noserim5.rotateAngleY = f3 / (180F / (float)Math.PI);
    Noserim6.rotateAngleY = f3 / (180F / (float)Math.PI);
    Nose.rotateAngleX = f4 / (180F / (float)Math.PI);
    Nose.rotateAngleY = f3 / (180F / (float)Math.PI);
    
  }

}
