// Date: 8/25/2014 7:44:11 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package securecraftprotect.client.model;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTileSlidingDoor extends ModelBase
{
    // fields
    ModelRenderer Door1;
    ModelRenderer Door2;
    
    public ModelTileSlidingDoor()
    {
        textureWidth = 80;
        textureHeight = 40;
        
        Door1 = new ModelRenderer(this, 0, 0);
        Door1.addBox(0F, 0F, 0F, 16, 32, 2);
        Door1.setRotationPoint(-8F, -8F, 0F);
        Door1.setTextureSize(80, 40);
        Door1.mirror = true;
        setRotation(Door1, 0F, 0F, 0F);
        Door2 = new ModelRenderer(this, 38, 0);
        Door2.addBox(0F, 0F, 0F, 16, 32, 2);
        Door2.setRotationPoint(-8F, -8F, -2F);
        Door2.setTextureSize(80, 40);
        Door2.mirror = true;
        setRotation(Door2, 0F, 0F, 0F);
    }
    
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        GL11.glPushMatrix();
        GL11.glTranslatef(0.0F + f, 0F, 0.0F);
        Door1.render(f5);
        GL11.glTranslatef(0.0F - f - f, 0F, 0.0F);
        Door2.render(f5);
        GL11.glPopMatrix();
    }
    
    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
    
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }
    
}
